spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shoestore?currentSchema=shoestore
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: false
    default-schema: shoestore
security:
  jwt:
    secret: Z2ZkZGZnZnRnZnNnZ2dmZ2RmaGdoZ2Zkd2dzZGZkZGZMS0hHQk5WVkZHR0VISkJO
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false
